max_jobs: 1

image: Visual Studio 2017

platform:
  - x86
  - x64
  - ARM

configuration:
  - Release
  - Debug

build:
  verbosity: minimal
  project: t1ha.sln

test_script:
- ps: |
    if (($env:PLATFORM -eq "x86") -and (Test-Path "C:\projects\t1ha\Win32\$env:CONFIGURATION\t1ha-test\t1ha-test.exe" -PathType Leaf)) {
      & "C:\projects\t1ha\Win32\$env:CONFIGURATION\t1ha-test\t1ha-test.exe"
    } elseif (($env:PLATFORM -ne "ARM") -and ($env:PLATFORM -ne "ARM64")) {
      & "C:\projects\t1ha\$env:PLATFORM\$env:CONFIGURATION\t1ha-test\t1ha-test.exe"
    }
